name: earned_it
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.0.0
  flutter_riverpod: ^2.6.1
  url_launcher: ^6.3.2
  toastification: ^3.0.3
  freezed: ^3.1.0
  sign_in_with_apple: ^7.0.1
  kakao_flutter_sdk: ^1.9.7+3
  flutter_dotenv: ^5.2.1
  # flutter_config: ^2.0.2
  retrofit: ^4.6.0
  logger: ^2.6.1
  json_annotation: ^4.9.0
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  retrofit_generator:
  build_runner: ^2.5.4
  json_serializable: ^6.9.5

flutter:

  uses-material-design: true

  assets:
    - assets/.env
    - assets/images/time.png
    - assets/images/kakao_login.png
    - assets/images/apple_login_light.png
    - assets/images/apple_login_dark.png

  fonts:
    - family: Mainfonts
      fonts:
        - asset: assets/fonts/WantedSans-Regular.ttf # 기본값
        - asset: assets/fonts/WantedSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WantedSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WantedSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/WantedSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/WantedSans-Black.ttf
          weight: 900