name: earned_it
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.8+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.0.0
  flutter_riverpod: ^2.6.1
  url_launcher: ^6.3.2
  toastification: ^3.0.3
  freezed: ^3.1.0
  sign_in_with_apple: ^7.0.1
  kakao_flutter_sdk: ^1.9.7+3
  flutter_dotenv: ^5.2.1
  # flutter_config: ^2.0.2
  retrofit: ^4.6.0
  logger: ^2.6.1
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  flutter_env_native: ^0.2.0
  animated_digit: ^3.2.3
  animated_toggle_switch: ^0.8.5
  carousel_slider: ^5.1.1
  action_slider: ^0.7.0
  shared_preferences: ^2.5.3
  lottie: ^3.3.1
  image_picker: ^1.1.2
  flutter_slidable: ^4.0.0
  flutter_launcher_icons: ^0.14.4
  image_cropper:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  retrofit_generator:
  build_runner: ^2.5.4
  json_serializable: ^6.9.5

flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/.env
    
    - assets/images/default_profile.png
    - assets/images/logo_light.png
    - assets/images/logo_dark.png
    - assets/images/time.png
    - assets/images/login/kakao_login.png
    - assets/images/login/apple_login_light.png
    - assets/images/login/apple_login_dark.png
    - assets/images/iphone.png
    - assets/images/macbook.png
    - assets/images/switch.png
    - assets/images/money/money_small.png
    - assets/images/money/money_middleSmall.png
    - assets/images/money/money_middle.png
    - assets/images/money/money_largeSmall.png
    - assets/images/money/money_largeMiddle.png
    - assets/images/piece/unknow_piece.png

    - assets/lottie/empty_wish.json
    - assets/lottie/check_wish.json
    - assets/lottie/isNot_Salary.json
    - assets/lottie/empty_piece.json

  fonts:
    - family: Mainfonts
      fonts:
        - asset: assets/fonts/WantedSans-Regular.ttf # 기본값
        - asset: assets/fonts/WantedSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WantedSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WantedSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/WantedSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/WantedSans-Black.ttf
          weight: 900