name: earned_it
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.0.0
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    # - assets/

  fonts:
    - family: Mainfonts
      fonts:
        - asset: assets/font/WantedSans-Regular.ttf # 기본값
        - asset: assets/font/WantedSans-Medium.ttf
          weight: 500
        - asset: assets/font/WantedSans-SemiBold.ttf
          weight: 600
        - asset: assets/font/WantedSans-Bold.ttf
          weight: 700
        - asset: assets/font/WantedSans-ExtraBold.ttf
          weight: 800
        - asset: assets/font/WantedSans-Black.ttf
          weight: 900